<a href="https://colab.research.google.com/github/vktorvini/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a Ciências de Dados


## NumPy

NumPy é a abreviatura de numerical Python.
É um dos pacotes mais importantes para o processamento numérico em Python.
Matemática é o CERNE do DS!!!

A maioria dos pacotes de processamento com funcionalidades científicas utiliza objetos array do NumPy.

Muito utilizado para array (listas) e também para array multidimensional com operações aritméticas rápidas, sem uso de laços.

Você Precisa dominar o NumPy e principalmente as estruturas de dados do Python, arrays multidimensionais principalmente.

Importar a biblioteca

In [ ]:
import numpy as np

#Gerar Dados Aleatórios

##Gerar um NDArray de 2x3 (duas listas com 3 elementos)

In [ ]:
dados = np.random.rand(2,3)


In [ ]:
dados

array([[0.26384423, 0.61970313, 0.06288073],
       [0.78976251, 0.00268402, 0.657852  ]])

##Tipos do Array

In [ ]:
dados.dtype


dtype('float64')

##Tamanho e quantidade de dimensão

In [ ]:
dados.shape

(2, 3)

In [ ]:
dados.ndim

2

# Criar ndarray usando a função array
## Ao criar a função array tenta utilizar o melhor tipo de dado

In [ ]:
lista=[1,2,5,7.8,1.25]

In [ ]:
dados2=np.array(lista)

In [ ]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [ ]:
lista2=[[1,2,3,4], [4,3,2,1]]

In [ ]:
dados3= np.array(lista2)

In [ ]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

# Outras Maneiras de Criar Arrays:

In [ ]:
dadoszero=np.zeros(10)

In [ ]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
dadoszero2 = np.zeros((2,3))

In [ ]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
dadosum= np.ones(5)

In [ ]:
dadosum

array([1., 1., 1., 1., 1.])

In [ ]:
dadosseq=np.arange(10)

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq2 = np.arange(0,20,2)

In [ ]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dadosseq.dtype

dtype('int64')

In [ ]:
dadosseqf=dadosseq.astype(np.float64)

In [ ]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
dadosseqf.dtype

dtype('float64')

# Artitmética com Arrays

In [ ]:
dados4 =np.array([[1,2,3],[4,5,6]])

In [ ]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
1 / dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
dados5 = dados4+dados4

In [ ]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
dados5 > dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

##Indexação

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq[5]

5

Diferente de uma lista python, um recorte(fatia) de um ndarray sofrerá um broadcast -
É como se fosse uma view de bano de dados.
Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [ ]:
dadosseq[3:6]

array([3, 4, 5])

In [ ]:
dadosseq[3:6]=20

In [ ]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [ ]:
fatiadados= dadosseq[2:4]

In [ ]:
fatiadados

array([ 2, 20])

In [ ]:
fatiadados[1]=2000

In [ ]:
fatiadados

array([   2, 2000])

In [ ]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [ ]:
fatiadados[:]=333

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

##Copiar Dados

In [ ]:
fatia2=dadosseq[2:4].copy()

In [ ]:
fatia2

array([333, 333])

In [ ]:
fatia2[:]=2

In [ ]:
fatia2

array([2, 2])

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Array com mais de uma dimensão

In [ ]:
dados6= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dados6[1,2]

6

Mascaras

In [ ]:
mascara=(dadosseq<100)

In [ ]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
dadosseq[dadosseq<20]=8888

In [ ]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#Transposição
Inverte a matriz de lado:

In [ ]:
dados7=np.arange(15).reshape((3,5))

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de Matrizes com Dots

In [ ]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])